resolver: lts-10.0

packages:
- .
# extra-deps: []
# flags: {}
# extra-package-dbs: []
# system-ghc: true
# require-stack-version: -any # Default
# require-stack-version: ">=1.7"
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
